### ISSUE TITLE
Logo Design and Color Scheme

### ISSUE THREAD

**Issue by osamamhd** [FotieMConstant/bond#48]
Simple logo for attention-grabbing with simple design and colors.
comment on what kind of logo you have in mind and I will work on the first design. (**Some Experiences in logo design**)

**color Scheme**
currently, the color scheme of the website is blue and white (**darkmode**).
we should choose 3 or 4 colors to be the overall scheme of the website.
comment on what color scheme you have in mind?

**Comment by FotieMConstant** [comment]
Hey there @osamamhd, thanks for opening this issue. the current color we use now is this (#fd4d4d) We try as much as possible to keep things simple(you can see that from the current logo in the repo). the be honest I don't personally have any other colors in mind. Well, you can recommend something in addition to the color I gave above!

Can't wait to see what you'll produce.

**Comment by FotieMConstant** [comment]
Hey there @osamamhd, thanks for opening this issue. the current color we use now is this (#fd4d4d) We try as much as possible to keep things simple(you can see that from the current logo in the repo). the be honest I don't personally have any other colors in mind. Well, you can recommend something in addition to the color I gave above!

Can't wait to see what you'll produce.

**Comment by osamamhd** [comment]
![g898](https://user-images.githubusercontent.com/15228467/115117097-3999e180-9f9d-11eb-8bab-6834a65d36b5.png)
@FotieMConstant hey man, I created three colors scheme including the color (#fd4d4d).

**Comment by FotieMConstant** [comment]
Wooohh hooHh!! Dude I absolutely love it... It's mind-blowing, I love the colours.

**Comment by FotieMConstant** [comment]
@quiet-programmer @dilanlongla @Jael-dev what are you thoughts?

**Comment by quiet-programmer** [comment]
@FotieMConstant ... Looks really nice dude... Awesome @osamamhd

**Comment by dilanlongla** [comment]
They look great @osamamhd and most importantly i am waiting for your logo proposal

**Comment by osamamhd** [comment]
thanks, guys :D, since everyone on board with the color scheme, I will start working on the logo.

**Comment by osamamhd** [comment]
![g2410](https://user-images.githubusercontent.com/15228467/115128489-5d314c00-9fde-11eb-8eed-8efb1cc47f31.png)
the initial idea and first sketch, what's your opinion @FotieMConstant @quiet-programmer @dilanlongla

**Comment by quiet-programmer** [comment]
@osamamhd ehnn... I'm not mush of a design person tho... but since you say this is the initial idea... let me just wait and see... and let @FotieMConstant come give his own tot on it

**Comment by FotieMConstant** [comment]
Looks good but I kinda think it's a little too sharp for a love thing... How about you go from what we have on the repo? in the readme that would be fantastic!

**Comment by osamamhd** [comment]
![rect1335](https://user-images.githubusercontent.com/15228467/115293823-11a2ad80-a158-11eb-92dc-82f6080a99ba.png)
As simple as possible. just like the readme with a little twist ... or we can leave as it is @FotieMConstant

**Comment by FotieMConstant** [comment]
Wow, I don't know about you guys but this logo is super clean and simple 😍😍

**Comment by quiet-programmer** [comment]
this is actually okay

**Comment by Jael-dev** [comment]
Aaaawwwww, si cute

**Comment by Jael-dev** [comment]
Awwwww, so cute

**Comment by Shows-creation** [comment]
> ![rect1335](https://user-images.githubusercontent.com/15228467/115293823-11a2ad80-a158-11eb-92dc-82f6080a99ba.png)
> As simple as possible. just like the readme with a little twist ... or we can leave as it is @FotieMConstant

hey bro i really want to talk with u for about a logo how can we meet> via discord??? urgent!

**Comment by Shows-creation** [comment]
> thanks, guys :D, since everyone on board with the color scheme, I will start working on the logo.

hey osamamhd i really wanna talk with u via discord about a logo can u plzz help me. it's urgent!!! i request u

**Comment by FotieMConstant** [comment]
I think this issue should be closed now!
