### ISSUE TITLE
Integrate the auth workflow on the frontend and Mobile App

### ISSUE THREAD

**Issue by FotieMConstant** [FotieMConstant/bond#76]
Backend is done for the auth. just need to implement that on the front end. Please can someone do that?
- endpoint ``https://bond-api.vercel.app/user``
- Method: `POST`
- Data(Send as an object in Body*): 
```
{
"uid": "uid from google auth",
"name": "name from google auth",
"username": "send empty string (User can update their username later after signin)",
"photo": "profileURL from google auth",
"email": "email from google auth"
}
```
RESPONSE
In case they already have an account in db
```
[
    {
        "status": "login",
        "message": "Thanos Logged in successfully!"
    }
]
```
In case it's their first time
```
[
    {
        "status": "signup",
        "message": "Thanos account created successfully!"
    }
]
```

**Comment by FotieMConstant** [comment]
@quiet-programmer @Jael-dev @TatchumNono can you check this out?

**Comment by quiet-programmer** [comment]
We can leave the user name as blank so the user can set it up themselves @FotieMConstant

**Comment by quiet-programmer** [comment]
The flow is better bro

**Comment by FotieMConstant** [comment]
great idea @quiet-programmer, you mean they can set it later run right? it's great idea

**Comment by quiet-programmer** [comment]
Yeah like return an empty string dere... And then after the user is signed in... He or she has to set the username themselves.... Cuz giving them random username ain't gonna look nice...

**Comment by FotieMConstant** [comment]
Just pushed the changes, in a PR #78

**Comment by FotieMConstant** [comment]
Okay, got it. thanks for the suggestion man

**Comment by FotieMConstant** [comment]
Hey @quiet-programmer how about we set it to `null`?
