### ISSUE TITLE
Suggestion Tab-Front

### ISSUE THREAD

**Issue by buaya123** [FotieMConstant/bond#97]
Is this a thing? do we make a suggestion tab where new users can choose to bond with people online or no?

**Comment by dilanlongla** [comment]
@buaya123 personally i don't think we will need this functionality for now, added that will make it sound like a dating app (which is not the idea behind bond)

**Comment by buaya123** [comment]
Yeah XD, I thought so

**Comment by FotieMConstant** [comment]
Thanks, @dilanlongla. I think this issue should be close now!
